version: '3.1'

services:

  rdb:
    build:
      context: ./postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: next-jdbc-basic
      #POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/conf:/etc/postgresql/
